version: '3.8'

services:
  db:
    image: mysql:8
    ports:
      - "3307:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: 'Chef@coding7' 
      MYSQL_DATABASE: 'poc'                

  backend:
    build:
      
      context: ./backend-poc
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      DB_HOSTNAME: 'db' 
      DB_USER: 'root'
      DB_PASSWORD: 'Chef@coding7'
      DB_DATABASE: 'poc'
    restart: on-failure
    depends_on:
      - db

  frontend:
    build:
      context: ./ui-poc
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
