version: '3.8'

services:
  backend:
    build:
      context: ./backend-poc
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    network_mode: host
    environment:
      DB_HOST: 127.0.0.1
      DB_USER: analytics_dev
      DB_PASSWORD: analytics
      DB_NAME: analytics
      DB_PORT: 3306
      PORT: 5000
    restart: on-failure

  frontend:
    build:
      context: ./ui-poc
      dockerfile: Dockerfile
    ports:
      - "4000:80"
    depends_on:
      - backend
